version: "3"

services:

  node1:
    build: .
    image: server
    ports:
        - "10000:9999"
    environment:
      PEERS: 'node2,node3'

  node2:
    image: server
    ports:
        - "10001:9999"
    environment:
      PEERS: 'node1,node3'

  node3:
    image: server
    ports:
        - "10002:9999"
    environment:
      PEERS: 'node1,node2'

